version: "3"
services:
  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    image: grpc-todo/user
    container_name: user
    ports:
      - "50051:50051"
    environment: 
      - "PROJECT_SERVICE_ADDR=project:50051"
    depends_on:
      - db
  task:
    build:
      context: .
      dockerfile: task/Dockerfile
    image: grpc-todo/task
    container_name: task
    ports:
      - "50052:50051"
    environment: 
      - "PROJECT_SERVICE_ADDR=project:50051"
    depends_on:
      - db
  project:
    build:
      context: .
      dockerfile: project/Dockerfile
    image: grpc-todo/project
    container_name: project
    ports:
      - "50053:50051"
    depends_on:
      - db
  db:
    image: mysql:8.0.24
    container_name: grpc-todo-db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: grpc_todo
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    image: grpc-todo/front
    container_name: front
    ports:
    - "8080:8080"
    environment:
    - "ACTIVITY_SERVICE_ADDR=activity:50051"
    - "PROJECT_SERVICE_ADDR=project:50051"
    - "USER_SERVICE_ADDR=user:50051"
    - "TASK_SERVICE_ADDR=task:50051"

volumes:
  db:
